all: clean
	@ echo "    * Building listener_LISTENER_ plugin"
	@ mkdir dist
	@ cp config.json ax_config.axs ./dist/
	@ go build -buildmode=plugin -ldflags="-s -w" -o ./dist/_LISTENER_.so pl_main.go pl_listener.go
	@ echo "      done..."

clean:
	@ rm -rf dist
